version: "3.9"
services:
  bee:
    container_name: bee
    # We can either build the Docker image
    build:
      context: ../../
      dockerfile: ./bee-node/docker/Dockerfile
      args:
        WITH_DASHBOARD: "true"
    # Or use an already created image by uncommenting the following line (and commenting the build section above)
    #image: bee:latest
    ulimits:
      nofile:
        soft: 8192
        hard: 8192
    stop_grace_period: 5m
    tty: true # for colored logs
    network_mode: host
    volumes:
      - ../config.chrysalis-mainnet.toml:/config.toml
      - ../storage:/storage
      - ../snapshots:/snapshots
