[package]
name = "bee-network"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Networking layer for the Bee framework"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "network"]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { version = "0.2.0-alpha", path = "../bee-common/bee-common" }
bee-runtime = { version = "0.1.0-alpha", path = "../bee-runtime" }

async-trait = "0.1"
futures = "0.3"
lazy_static = "1.4"
libp2p = { version = "0.29", default-features = false, features = ["dns", "mplex", "noise", "tcp-tokio", "yamux"]}
log = "0.4"
serde = { version = "1.0", features = ["derive" ] }
thiserror = "1.0"
tokio = { version = "0.2", features = ["dns", "time", "tcp", "io-util", "stream"] }
url = "2.1"

[dev-dependencies]
bee-test = { path = "../bee-test" }

anymap = "0.12"
env_logger = "0.7"
pretty_env_logger = "0.4"
serde = { version = "1.0", features = ["derive" ] }
structopt = "0.3"
tokio = { version = "0.2", features = ["full"] }
