[package]
name = "bee-common"
version = "0.4.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Common utilities used across the bee framework"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "common"]
homepage = "https://www.iota.org"

[dependencies]
chrono = "0.4"
fern = { version = "0.6", features = ["colored"] }
log = { version = "0.4", features = ["serde"] }
rand = { version = "0.8", optional = true }
rust-argon2 = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive" ] }
thiserror = "1.0"

[build-dependencies]
autocfg = "1.0"

[features]
password = [ "rand", "rust-argon2" ]
