[package]
name = "bee-common"
version = "0.2.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Common utilities used across the bee framework"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "common"]
homepage = "https://www.iota.org"

[dependencies]
chrono = "0.4"
dashmap = "3.11"
fern = { version = "0.6", features = ["colored"] }
futures = "0.3"
log = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive" ] }
thiserror = "1.0"

[dev-dependencies]
async-std = { version = "1.6", features = [ "attributes" ] }
