[package]
name = "bee-packable"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "Serialization and deserialization primitives for the bee framework"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "packable" ]
homepage = "https://www.iota.org"

[features]
io = []

[build-dependencies]
autocfg = "1.0"

[dependencies]
bee-packable-derive = { path = "../bee-packable-derive" }
serde = { version = "1.0", features = [ "derive" ], optional = true }
