[package]
name = "bee-test"
version = "0.1.0"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Test utilities and feature tests for bee"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "test"]
homepage = "https://www.iota.org"

[dependencies]
bee-ledger = { version = "0.5.0", path = "../bee-ledger" }
bee-message = { version = "0.1.5", path = "../bee-message" }
bee-tangle = { version = "0.1.2", path = "../bee-tangle" }
bee-ternary = { version = "0.4.2-alpha", features = [ "serde1" ], path = "../bee-ternary" }

bytemuck = "1.7"
rand = "0.8"

[dev-dependencies]
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
