[package]
name = "bee-test"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = "Test utilities and feature tests for bee"
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "test"]
homepage = "https://www.iota.org"

[dependencies]
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-ledger = { path = "../bee-ledger", features = [ "snapshot" ] }
bee-message = { path = "../bee-message" }
bee-pow = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-storage = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-tangle = { path = "../bee-tangle" }
bee-ternary = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }

bytemuck = "1.5"
futures = "0.3"
num_cpus = "1.12"
rand = "0.8"
serde = "1.0"
tokio = { version = "1.4", features = [] }
