[package]
name = "bee-ledger"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "ledger"]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev", optional = true }
bee-message = { path = "../bee-message" }
bee-runtime = { git = "https://github.com/iotaledger/bee.git", branch = "dev", optional = true }
bee-storage = { git = "https://github.com/iotaledger/bee.git", branch = "dev", optional = true }
bee-tangle = { path = "../bee-tangle", optional = true }
bee-ternary = { git = "https://github.com/iotaledger/bee.git", branch = "dev", optional = true }

async-trait = { version = "0.1", optional = true }
chrono = { version = "0.4", optional = true }
digest = { version = "0.9", optional = true }
futures = { version = "0.3", optional = true }
hex = { version = "0.4", optional = true }
iota-crypto = { git = "https://github.com/iotaledger/crypto.rs", rev = "c3bf565eba62d0b81144174c2ff917bfde282e49", features = ["blake2b"], optional = true }
log = { version = "0.4", optional = true }
reqwest = { version = "0.11", features = ["stream"], optional = true }
serde = { version = "1.0", features = ["derive" ], optional = true }
thiserror = { version = "1.0" }
tokio = { version = "1.4", features = ["sync"], optional = true }
tokio-stream = { version = "0.1", optional = true }

[dev-dependencies]
rand = "0.8"

[features]
consensus = [
  "bee-crypto",
  "bee-runtime",
  "bee-storage",
  "bee-tangle",
  "bee-ternary",
  "async-trait",
  "digest",
  "futures",
  "hex",
  "iota-crypto",
  "log",
  "serde",
  "tokio",
  "tokio-stream"
]
snapshot = [
  "async-trait",
  "chrono",
  "futures",
  "log",
  "reqwest",
  "serde",
  "tokio"
]
pruning = []
