[package]
name = "bee-ledger"
version = "0.1.0-alpha"
authors = ["IOTA Stiftung"]
edition = "2018"
description = ""
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = ["iota", "tangle", "bee", "framework", "ledger"]
homepage = "https://www.iota.org"

[dependencies]
bee-common = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-crypto = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-message = { path = "../bee-message" }
bee-runtime = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-storage = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }
bee-tangle = { path = "../bee-tangle" }
bee-ternary = { git = "https://github.com/iotaledger/bee.git", branch = "dev" }

async-trait = "0.1"
blake2 = "0.9"
bytemuck = "1.2"
digest = "0.9"
futures = "0.3"
hex = "0.4"
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.0", features = ["sync"] }
tokio-stream = "0.1"

[dev-dependencies]
bee-test = { path = "../bee-test" }

hex = "0.4"
rand = "0.8"
