[package]
name = "bee-event-bus"
version = "0.1.0"
authors = [ "IOTA Stiftung" ]
edition = "2018"
description = "A generic, type-safe and thread-safe event bus for arbitrary event types."
readme = "README.md"
repository = "https://github.com/iotaledger/bee"
license = "Apache-2.0"
keywords = [ "iota", "tangle", "bee", "framework", "event" ]
homepage = "https://www.iota.org"

[dev-dependencies]
criterion = { version = "0.3.5", default-features = false }

[[bench]]
name = "event_bus"
harness = false
